### ISSUE TITLE
Train YOLO V3

### ISSUE THREAD

**Issue by richipower** [the-house-of-black-and-white/hall-of-faces#3]
Hello!

i used your YOLO version and it has great results, i would like to do the same but with the YOLO V3. I plan to train it on the WIDER Dataset but i wanted to ask you, how did you generate the labels from WIDER to YOLO format? do you have a small script to convert the data format?
Do you have details on your training process?

Thanks and greetz!

**Comment by fabito** [comment]
Hi @richipower ,

There is a library called [morghulis](https://github.com/the-house-of-black-and-white/morghulis) that I created just for dataset preparation and convertion between the most used formats.

And regarding training details, I think the cfg files are in the tar.gz I reference in the readme.
