### ISSUE TITLE
pipeline.config for mobilenet v1 ssd ?

### ISSUE THREAD

**Issue by jamessmith90** [the-house-of-black-and-white/hall-of-faces#4]
Hi,

I have been struggling to train object detection in Tensorflow for the last 2 months. Bugs and different versions are creating a mess. 

If you share the pipeline.config file for **mobilenet v1 ssd** it will help a lot in learning.
Also what **version** of Tensorflow did you use for training ?

Thanks for sharing your knowledge.

**Comment by fabito** [comment]
I used this configuration:

https://gist.github.com/fabito/754291381b5604fad62f9e99f4327747
